const fs = require('fs');
const path = require('path');

const LANGUAGE_CONTEXT_PATH = path.join(__dirname, '..', 'src', 'contexts', 'LanguageContext.tsx');
const MISSING_KEYS_PATH = path.join(__dirname, 'missing_keys.json');

// Comprehensive translation map for missing keys
const translationMap = {
    // Navigation
    'nav.home': '소사이어티',
    'nav.plaza': '광장',
    'nav.shop': '상점',
    'nav.stay': '스테이',
    'nav.rental': '대관',
    'nav.venues': '베뉴',
    'nav.groups': '그룹',
    'nav.explore': '점프',
    'nav.hub': '허브',
    'nav.resale': '리세일',
    'nav.pics': '사진',
    'nav.class': '클래스',
    'nav.now': '현재',
    'nav.social': '소셜',
    'nav.events': '이벤트',
    'nav.live': '라이브',
    'nav.lost_found': '분실물',
    'nav.history': '내역',
    'nav.wallet': '지갑',
    'nav.my_info': '프로필',
    'nav.people': '피플',
    'nav.place': '장소',
    'nav.others': '기타',
    'nav.world': '월드',
    'nav.market': '마켓',
    'nav.lounge': '라운지',
    'nav.activity': '활동',
    'nav.town': '타운',
    'nav.my': '나의 정보',
    'nav.support': '지원',
    'nav.language_selector': '언어 선택',
    'nav.app_setting': '앱 설정',
    'nav.logout': '로그아웃',
    'nav.tango_world': '탱고 월드',
    'nav.go_to_landing': '랜딩 페이지로 이동',

    // Header
    'header.home': '소사이어티',
    'header.plaza': '광장',
    'header.venues': '베뉴',
    'header.groups': '그룹',
    'header.social': '소셜',
    'header.class': '클래스',
    'header.events': '이벤트',
    'header.live': '라이브',
    'header.shop': '상점',
    'header.stay': '스테이',
    'header.freestyle_tango': '프리스타일 탱고',
    'header.service': '서비스',
    'header.resale': '리세일',
    'header.lost_found': '분실물 센터',
    'header.hub': '허브',
    'header.pics': '사진',
    'header.chat': '채팅',
    'header.wallet': '지갑',
    'header.history': '내역',
    'header.my_info': '내 정보',
    'header.community': '커뮤니티',
    'header.explore': '점프',
    'header.help_desk': '헬프 데스크',

    // Calendar
    'calendar.scheduleRegister': '일정 등록',
    'calendar.saving': '저장 중...',
    'calendar.save': '저장',
    'calendar.title': '제목',
    'calendar.eventTitle': '이벤트 제목',
    'calendar.category': '카테고리',
    'calendar.startsLabel': '시작',
    'calendar.endsLabel': '종료',
    'calendar.descriptionLabel': '설명',
    'calendar.addDetailsPlaceholder': '상세 내용 추가...',
    'calendar.noEvents': '일정 없음',
    'calendar.addSchedule': '일정 추가',
    'calendar.noEventsThisWeek': '이번 주 일정이 없습니다',
    'calendar.todayComma': '오늘, ',
    'calendar.edit': '수정',
    'calendar.delete': '삭제',
    'calendar.noEventsScheduledForThisDay': '이 날의 일정이 없습니다',
    'calendar.instructor': '강사',
    'calendar.level': '레벨',
    'calendar.scheduleUpdatedSuccessfully': '일정이 성공적으로 업데이트되었습니다.',
    'calendar.scheduleAddedSuccessfully': '일정이 성공적으로 추가되었습니다.',
    'calendar.permissionDenied': '권한이 없습니다. Firestore 보안 규칙을 확인하세요.',
    'calendar.failedToSaveSchedule': '일정 저장에 실패했습니다.',
    'calendar.confirmDeleteEvent': '이 이벤트를 삭제하시겠습니까?',
    'calendar.scheduleDeletedSuccessfully': '일정이 성공적으로 삭제되었습니다.',
    'calendar.failedToDeleteSchedule': '일정 삭제에 실패했습니다.',
    'calendar.classLabel': '클래스',
    'calendar.milongaLabel': '밀롱가',
    'calendar.socialLabel': '소셜',
    'calendar.practiceLabel': '프락티카',
    'calendar.generalLabel': '일반',
    'calendar.rentalLabel': '대관',
    'calendar.eventLabel': '이벤트',

    // Chatroom
    'chatroom.anonymous': '익명',
    'chatroom.unknown': '알 수 없음',
    'chatroom.default_location': '대한민국 서울',
    'chat.unknown_user': '알 수 없는 사용자',
    'chat.default_chat_name': '채팅',
    'chatroom.parse.tag.order_placed': '[주문 완료]',
    'chatroom.parse.tag.payment_reported': '[결제 보고됨]',
    'chatroom.parse.tag.product_inquiry': '[상품 문의]',
    'chatroom.parse.tag.stay_booking': '[스테이 예약]',
    'chatroom.parse.tag.stay_payment': '[스테이 결제]',
    'chatroom.parse.tag.rental_inquiry': '[렌탈 문의]',
    'chatroom.parse.key.order_no': '주문 번호',
    'chatroom.parse.key.product': '상품명',
    'chatroom.parse.key.option': '옵션',
    'chatroom.parse.key.amount': '금액',
    'chatroom.parse.key.image': '이미지',
    'chatroom.parse.key.depositor': '입금자명',
    'chatroom.parse.key.brand': '브랜드',
    'chatroom.parse.key.title': '제목',
    'chatroom.parse.key.price': '가격',
    'chatroom.parse.key.link': '링크',
    'chatroom.parse.key.stay': '스테이',
    'chatroom.parse.key.dates': '날짜',
    'chatroom.parse.key.nights': '숙박 일수',
    'chatroom.parse.key.guests': '인원',
    'chatroom.parse.key.applicant': '예약자',
    'chatroom.parse.key.space': '공간',
    'chatroom.parse.key.date': '날짜',
    'chatroom.parse.key.time': '시간',
    'chatroom.parse.key.purpose': '목적',
    'chatroom.parse.key.headcount': '인원',
    'chatroom.parse.key.message': '메시지',

    // Help Desk
    'help_desk.anonymous': '익명',
    'help_desk.title': '헬프 데스크',
    'help_desk.desc': 'WoC에 대해 무엇이든 물어보세요!',
    'help_desk.placeholder': '어떻게 도와드릴까요?',
    'help_desk.ai_thinking': 'AI가 생각하는 중...',
    'help_desk.official': '공식 지원',
    'help_desk.welcome': '환영합니다!',

    // Feed
    'feed.create_post': '게시물 작성',
    'feed.edit_post': '게시물 수정',
    'feed.posting': '게시 중...',
    'feed.updating': '업데이트 중...',
    'feed.post': '게시',
    'feed.update': '업데이트',
    'feed.style_available': '✨스타일 적용 가능',
    'feed.palette': '팔레트',
    'feed.style': '스타일',
    'feed.media': '미디어',
    'feed.add': '추가',
    'feed.add_photos_video': '사진 또는 비디오 추가',
    'feed.photo_count': '사진',
    'feed.video_count': '비디오',
    'feed.tags': '태그',
    'feed.tag_placeholder': '사람, 그룹, 이벤트, 소셜...',
    'feed.upload_in_progress': '업로드 중입니다. 잠시 후 다시 시도하세요.',
    'feed.max_video': '비디오는 최대 1개까지 추가할 수 있습니다.',
    'feed.max_images': '사진은 최대 20개까지 추가할 수 있습니다.',
    'feed.click_to_edit': '텍스트를 클릭하여 수정',
    'feed.style_normal': '보통',
    'feed.style_bold': '굵게',
    'feed.style_impact': '임팩트',
    'feed.style_italic': '이탤릭',
    'feed.style_uppercase': '대문자',

    // Home
    'home.hero_upcoming': '예정된 이벤트',
    'home.hero_title': '글로벌 탱고 이벤트를 발견하세요',
    'home.hero_desc': '커뮤니티의 다음 흥미로운 이벤트를 기대해 주세요.',
    'home.hero_explore': '탐색하기',
    'home.see_translation_1': '번역',
    'home.see_translation_2': '보기',
    'home.show_original_1': '원본',
    'home.show_original_2': '보기',
    'home.live_in_seoul': '내 주변 라이브',
    'home.view_all': '전체 보기',
    'home.no_live_posts': '아직 라이브 게시물이 없습니다',
    'home.go_to_live': '라이브로 이동 \u2192',
    'home.stories_from_seoul': '서울의 이야기들',
    'home.no_stories_yet': '아직 이야기가 없습니다. ',
    'home.visit_plaza': '광장 방문하기 \u2192',
    'home.across_world': '전 세계 소식',
    'home.global_updates': '글로벌 업데이트',
    'home.explore_seoul': '서울 탐색하기',
    'home.find_venues': '베뉴 찾기',
    'home.find_venues_desc': '서울에서 가장 좋은 밀롱가 장소를 찾아보세요.',
    'home.stay_nearby': '주변 숙소',
    'home.stay_nearby_desc': '페스티벌 장소와 가까운 엄선된 숙소들.',
    'home.join_class': '클래스 참여',
    'home.join_class_desc': '내 레벨에 맞는 완벽한 탱고 클래스를 찾아보세요.',
    'home.rent_studio': '스튜디오 대관',
    'home.rent_studio_desc': '개인 연습을 위한 프라이빗 스튜디오 대여.',
    'home.culture_canvas': '컬처 & 캔버스',
    'home.gavi_cartoons': '가비의 카툰',
    'home.gavi_cartoons_desc': '네 컷 만화로 담아낸 우리의 일상',
    'home.tango_music': '탱고 뮤직 365',
    'home.tango_music_desc': 'Camus가 준비 중인 고품질 음악 방송',
    'home.tango_history': '탱고의 역사',
    'home.tango_history_desc': 'Ddakji의 책을 통해 탱고의 역사를 공부하세요',
    'home.tango_novel': '탱고 소설',
    'home.tango_novel_desc': '춤에서 영감을 받은 이야기들',
    'home.tango_travel': 'Beto의 탱고 여행',
    'home.tango_travel_desc': '여러 나라의 밀롱가와 이벤트 경험을 공유합니다',
    'home.people_to_know': '알아야 할 인물들',
    'home.feel_moment': '순간을 느끼세요',
    'home.live_streams_title': '전 세계 실시간 밀롱가 스트리밍',
    'home.live_streams_desc': '부에노스아이레스, 도쿄, 이스탄불, 다낭 등에서 열리는 실시간 밀롱가를 시청하세요. 글로벌 탱고 커뮤니티를 실시간으로 경험하세요.',
    'home.live_streams_soon': '곧 출시 예정 — 이벤트가 시작되면 라이브 스트리밍을 이용할 수 있습니다.',
    'home.photo_video_awards': '포토제닉 & 비디오제닉 어워드',
    'home.photo_video_desc': '밀롱가와 파티에서 가장 아름다운 순간들을 선정합니다. 커뮤니티의 렌즈를 통해 탱고의 아름다움을 담아보세요.',
    'home.nominations_open': '라이브 이벤트 중 후보 등록이 열립니다.',
    'home.footer_rights': '©2026 World of Community. 모든 권리 보유',
    'common.footer_rights': '©2026 World of Community. 모든 권리 보유',

    // Auth
    'auth.title_signin': 'WoC : 탱고 소사이어티 로그인',
    'auth.title_register': 'WoC : 탱고 소사이어티 회원가입',
    'auth.headline_more': '추가 정보 입력',
    'auth.headline_verify': '전화번호 인증',
    'auth.headline_join': '함께하기',
    'auth.desc_more': '남은 세부 정보를 입력해 주세요.',
    'auth.desc_input': '전화번호를 입력해 주세요.',
    'auth.desc_verify': '인증 번호를 입력해 주세요.',
    'auth.desc_join': '탱고 소사이어티에 오신 것을 환영합니다.',
    'auth.continue_phone': '전화번호로 계속하기',
    'auth.other_methods': '다른 방법으로 로그인',
    'auth.phone_label': '전화번호',
    'auth.send_code': '코드 전송',
    'auth.sending_code': '코드 전송 중...',
    'auth.back': '뒤로',
    'auth.code_label': '6자리 코드',
    'auth.verify_code': '코드 확인',
    'auth.country': '국가',
    'auth.select_country': '국가 선택',
    'auth.country_kr': '대한민국 (KR)',
    'auth.country_us': '미국 (US)',
    'auth.country_gb': '영국 (GB)',
    'auth.country_fr': '프랑스 (FR)',
    'auth.country_jp': '일본 (JP)',
    'auth.country_cn': '중국 (CN)',
    'auth.country_de': '독일 (DE)',
    'auth.country_ca': '캐나다 (CA)',
    'auth.country_au': '호주 (AU)',
    'auth.country_sg': '싱가포르 (SG)',
    'auth.english_nickname': '영문 닉네임',
    'auth.gender': '성별',
    'auth.gender_male': '남성',
    'auth.gender_female': '여성',
    'auth.gender_other': '기타',
    'auth.native_nickname': '현지어 닉네임',
    'auth.native_nickname_placeholder': '예: 스칼렛',
    'auth.complete_reg_btn': '회원가입 완료',
    'auth.terms_agree': '계속 진행함으로써 다음에 동의하게 됩니다: ',
    'auth.terms': '이용 약관',
    'auth.and': ' 및 ',
    'auth.privacy': '개인정보 처리방침',
    'auth.period': '.',
    'auth.alert_login_failed': '로그인 실패: ',
    'auth.alert_invalid_phone': '유효한 전화번호를 입력해 주세요.',
    'auth.alert_sms_failed': 'SMS 전송 실패: ',
    'auth.alert_enter_code': '인증 번호를 입력해 주세요.',
    'auth.alert_invalid_code': '유효하지 않은 코드: ',
    'auth.alert_verify_first': '먼저 본인 인증을 진행해 주세요.',
    'auth.alert_fill_fields': '모든 필수 항목을 입력해 주세요.',
    'auth.alert_reg_failed': '회원가입 실패: ',
    'auth.push_noti_title': '알림 설정',
    'auth.push_noti_desc': '이벤트, 메시지 및 업데이트에 대한 알림을 받아보세요.',
    'auth.push_noti_enable': '활성화',
    'auth.push_noti_success': '알림이 활성화되었습니다!',
    'auth.push_noti_blocked': '알림이 차단되었습니다. 브라우저 설정에서 활성화해 주세요.',
    'auth.enter_6_digits': '6자리 숫자를 입력하거나 아래 키패드를 누르세요.',
    'auth.resend_code': '코드 재전송',
    'auth.error.too_many_requests': '너무 많은 시도가 있었습니다. 잠시 후 다시 시도하세요.',
    'auth.error.invalid_verification_code': '유효하지 않은 인증 코드입니다. 다시 확인해 주세요.',
    'auth.error.code_expired': '인증 코드가 만료되었습니다. 새 코드를 요청하세요.',
    'auth.error.invalid_phone_number': '유효하지 않은 전화번호입니다.',
    'auth.error.network_request_failed': '네트워크 오류가 발생했습니다. 연결을 확인하세요.',
    'auth.error.quota_exceeded': 'SMS 할당량이 초과되었습니다. 나중에 다시 시도하세요.',
    'auth.error.captcha_check_failed': '보안 확인에 실패했습니다. 다시 시도해 주세요.',
    'auth.error.fallback': '오류: ',
    'auth.error.email_password_required': '이메일과 비밀번호를 모두 입력해 주세요.',
    'auth.error.password_length': '비밀번호는 최소 6자 이상이어야 합니다.',
    'auth.error.invalid_password': '유효하지 않은 비밀번호입니다.',
    'auth.error.timeout': '인증 시간이 너무 오래 걸립니다. Safari나 Chrome에서 다시 시도해 주세요.',
    'auth.email': '이메일',
    'auth.password': '비밀번호',
    'auth.email_continue': '이메일로 계속하기',
    'auth.auto_register_notice': '계정이 없다면 자동으로 생성됩니다.',
    'auth.soon': '곧 출시 예정',

    // Common
    'common.later': '나중에',
    'common.user': '사용자',
    'common.members': '멤버',
    'common.days.sun': '일',
    'common.days.mon': '월',
    'common.days.tue': '화',
    'common.days.wed': '수',
    'common.days.thu': '목',
    'common.days.fri': '금',
    'common.days.sat': '토',
    'common.role.dancer': '댄서',
    'common.role.organizer': '오거나이저',
    'common.role.instructor': '강사',
    'common.role.provider': '제공자',
    'common.nav_home': '홈',
    'common.nav_search': '검색',
    'common.nav_post': '게시',
    'common.nav_activity': '활동',
    'common.nav_profile': '프로필',
    'common.submit': '등록',
    'common.todo_message': '디자인 및 기획 중...',
    'common.optimizing': '최적화 중...',
    'common.uploading': '업로드 중...',
    'common.liked': '명이 좋아함',
    'common.dayLabel': '일',
    'common.weekLabel': '주',
    'common.monthLabel': '월',
    'common.search': '검색',
    'common.loading': '로딩 중...',
    'common.pull_to_refresh': '당겨서 새로고침',
    'common.release_to_refresh': '놓아서 새로고침',
    'common.updating': '업데이트 중...',
    'common.pull_down_to_refresh': '당겨서 새로고침',
    'common.share_not_supported': '이 브라우저에서는 공유 기능을 지원하지 않습니다',

    // Guard
    'guard.title': '브라우저에서 열기',
    'guard.desc_en': 'For the best experience, open this page in your default browser.',
    'guard.desc_kr': '외부 브라우저에서 열면 더 안정적으로 이용할 수 있습니다.',
    'guard.url_copied': 'URL이 복사되었습니다! 브라우저에 붙여넣으세요.',
    'guard.open_btn': '브라우저에서 열기',
    'guard.continue_btn': '그냥 계속하기',
    'guard.prompt_copy': '이 URL을 복사하여 Safari에서 여세요:',

    // Group
    'group.tab.brand': '브랜드 설정',
    'group.tab.dashboard': '대시보드',
    'group.tab.live': '라이브',
    'group.tab.feed': '피드',
    'group.tab.calendar': '캘린더',
    'group.tab.notice': '공지사항',
    'group.tab.about': '정보',
    'group.tab.members': '멤버',
    'group.tab.class': '수업 설정',
    'group.tab.stay': '스테이 설정',
    'group.tab.shop': '상점 설정',
    'group.tab.rental': '대관 설정',
    'group.tab.roles': '역할 및 권한',
    'group.tab.qa': 'Q&A 게시판',
    'group.tab.polls': '투표',
    'group.tab.attendance': '출석',
    'group.tab.broadcast': '방송',
    'group.tab.rules': '규칙',
    'group.tab.surveys': '설문조사',
    'group.tab.anonymous': '익명',
    'group.tab.classA': '클래스 A',
    'group.tab.classB': '클래스 B',
    'group.tab.classC': '클래스 C',
    'group.tab.homework': '숙제',
    'group.tab.studentReports': '보고서',
    'group.tab.tuition': '수강료',
    'group.tab.gradeSystem': '성적',
    'group.tab.parentNotify': '알림',
    'group.tab.parentConsult': '상담',
    'group.tab.examScheduler': '시험',
    'group.tab.ticketBooking': '티켓',
    'group.tab.workshopReg': '워크숍',
    'group.tab.qrCheckin': 'QR 체크인',
    'group.tab.waitlist': '대기 명단',
    'group.tab.retreat': '리트릿',
    'group.tab.eventStaff': '스태프',
    'group.tab.guestList': '게스트',
    'group.tab.taskManager': '업무 관리',
    'group.tab.internalWiki': '위키',
    'group.tab.productInventory': '재고',
    'group.tab.membershipBilling': '청구',
    'group.tab.donationSupport': '후원',
    'group.tab.subscriptionPlans': '구독',
    'group.tab.settlementReports': '정산',
    'group.tab.mediaGallery': '미디어',
    'group.tab.videoLibrary': '비디오',
    'group.tab.editorialPage': '에디토리얼',
    'group.tab.newsletter': '뉴스레터',
    'group.tab.podcastFeed': '팟캐스트',
    'group.tab.pressKit': '프레스 키트',
    'group.tab.linkHub': '링크 허브',
    'group.tab.socialSync': '소셜 연동',
    'group.tab.brandAssets': '자산',
    'group.tab.customLandingPage': '랜딩',
    'group.tab.aiAssistant': 'AI 지원',
    'group.home.moments': '순간들',
    'group.home.live_chatter': '라이브 채팅',
    'group.home.coming_hot': '최신 소식',
    'groups.new_members_label': '이번 주 새 멤버',
    'group.class.coming_soon': '클래스 관리 기능이 준비 중입니다. 기대해 주세요!',

    // Shop
    'shop.sort_latest': '최신순',
    'shop.sort_sale': '세일순',
    'shop.sort_popular': '인기순',
    'shop.sort_new': '신규순',
    'shop.sort_price_asc': '가격 낮은순 ↑',
    'shop.sort_price_desc': '가격 높은순 ↓',
    'shop.filter_all': '전체',
    'shop.filter_shoes': '슈즈',
    'shop.filter_woman_shoes': '여성 슈즈',
    'shop.filter_man_shoes': '남성 슈즈',
    'shop.filter_wear': '의류',
    'shop.filter_woman_wear': '여성 의류',
    'shop.filter_man_wear': '남성 의류',
    'shop.filter_item': '아이템',
    'shop.msg_login_first': '먼저 로그인해 주세요',
    'shop.items': '상품',
    'shop.brand': '브랜드',
    'shop.sort': '정렬',
    'shop.filter_by_brand': '브랜드별 필터',
    'shop.close_filter': '필터 닫기',
    'shop.no_sale_items': '세일 상품이 없습니다',
    'shop.no_new_arrivals': '이번 주 신상품이 없습니다',
    'shop.no_products': '상품을 찾을 수 없습니다',
    'shop.no_image': '이미지 없음',
    'shop.new_season': '뉴 시즌',
    'shop.hero_title': '프로 탱고 슈즈',
    'shop.hero_desc': '우아함과 정교함을 위해 설계되었습니다.',
    'shop.hero_btn': '컬렉션 보기',
    'shop.opt_width': '발볼 넓이',
    'shop.val_regular': '보통',
    'shop.val_wide': '넓음',
    'shop.val_extra_wide': '매우 넓음',
    'shop.opt_heel_height': '굽 높이',
    'shop.opt_outsole': '아웃솔',
    'shop.val_leather': '가죽',
    'shop.val_rubber': '고무',
    'shop.val_suede': '스웨이드',
    'shop.val_standard': '표준',
    'shop.msg_no_self_chat': '자기 자신과는 채팅할 수 없습니다',
    'shop.msg_inquiry_chat': '판매자에게 상품 문의 채팅을 보내시겠습니까?',
    'shop.only_left': '단',
    'shop.left': '개 남음',
    'shop.in_stock': '재고 있음',
    'shop.viewing_now': '명이 보고 있음',
    'shop.fit_options': '핏 및 옵션',
    'shop.no_customization': '이 상품은 커스텀이 불가능합니다',
    'shop.contact_seller_special': '특별 요청은 판매자에게 문의하세요',
    'shop.size_guide': '사이즈 가이드',
    'shop.contact_seller_size': '상세 사이즈는 판매자에게 문의하세요.',
    'shop.option_details': '옵션 상세',
    'shop.available_sizes': '이 상품의 사용 가능한 사이즈.',
    'shop.required': '필수',
    'shop.width_desc': '발 모양에 맞는 넓이를 선택하세요. 넓은 옵션은 앞부분에 추가 공간을 제공합니다.',
    'shop.heel_desc': '선호하는 굽 높이를 선택하세요. 높은 굽은 퍼포먼스 시 더 우아한 실루엣을 제공합니다.',
    'shop.outsole_desc': '아웃솔 소재는 그립과 슬라이드에 영향을 줍니다. 스웨이드는 실내 댄스 플로어에서 인기가 많습니다.',
    'shop.included': '포함됨',
    'shop.available_same_brand': '동일 브랜드 구매 시 가능',
    'shop.repurchase_coupon_issued': '재구매 쿠폰 발행됨 · My > 쿠폰',
    'shop.no_purchase_coupon': '구매 쿠폰 없음',
    'shop.payment_bank_transfer': '결제 방법: 무통장 입금',
    'shop.store_pickup': '매장 픽업',
    'shop.delivery': '배송',
    'shop.production_delivery': '제작 및 배송',
    'shop.production': '제작',
    'shop.days': '일',
    'shop.approx': '약',
    'shop.default_production_days': '7~14일 (예상)',
    'shop.pickup_desc': '제작 완료 후 수령 가능 · 배송비 없음',
    'shop.days_after_production': '일 (제작 후)',
    'shop.default_delivery_days': '제작 완료 후 2~5일',
    'shop.shipping_paid_by_seller': ' · 판매자 부담',
    'shop.shipping_fee_prefix': ' · 배송비 ₩',
    'shop.free_shipping': ' · 무료 배송',
    'shop.free_exchange': '무료 교환',
    'shop.description': '상세 설명',
    'shop.no_description': '상세 설명이 없습니다.',
    'shop.less': '접기',
    'shop.more': '더 보기',
    'shop.chat_with_seller': '판매자와 채팅하기',
    'shop.product_info_auto_sent': '상품 정보가 자동으로 전송됩니다',
    'shop.list_price': '정가 ₩',
    'shop.options_add_price': ' · 옵션 +₩',
    'shop.purchase': '구매하기',
    'shop.size': '사이즈',
    'shop.msg_enter_contact': '판매자가 연락할 수 있도록 연락처를 입력해 주세요.',
    'shop.order_summary': '주문 요약',
    'shop.contact_number': '연락처',
    'shop.seller_contact_notice': '판매자가 주문에 대해 이 번호로 연락드릴 것입니다.',
    'shop.processing': '처리 중...',
    'shop.confirm': '확인',
    'shop.confirm_agreement': '확인 버튼을 누르면 1시간 이내에 입금하는 것에 동의하게 됩니다.',
    'shop.payment_instructions': '결제 안내',
    'shop.transfer_within_1h': '1시간 이내에 입금해 주세요.',
    'shop.order_expire_notice': '시간 내에 결제되지 않으면 주문이 만료될 수 있습니다.',
    'shop.order_number': '주문 번호',
    'shop.copied': '✓ 복사됨',
    'shop.copy': '복사',
    'shop.bank_transfer_details': '무통장 입금 상세',
    'shop.bank': '은행',
    'shop.account_number': '계좌 번호',
    'shop.account_holder': '예금주',
    'shop.transfer_amount': '입금 금액',
    'shop.how_it_works': '진행 방식',
    'shop.step1_title': '금액 입금',
    'shop.step1_desc': '1시간 이내에 위 계좌로 정확한 금액을 송금하세요.',
    'shop.step2_title': '판매자 입금 확인',
    'shop.step2_desc': '판매자가 송금을 확인하고 주문을 승인합니다.',
    'shop.step3_title': '제작 시작',
    'shop.step3_desc': '상품은 {min}–{max}일 이내에 제작됩니다.',
    'shop.step4_pickup_title': '매장 수령',
    'shop.step4_delivery_title': '배송 시작',
    'shop.step4_delivery_desc': '제작 완료 후 {days}일 이내에 배송됩니다.',
    'shop.payment_warning': '1시간 이내에 결제가 완료되지 않으면 주문이 자동으로 취소됩니다.',
    'shop.order_placed': '주문이 접수되었습니다!',
    'shop.order_placed_desc1': '주문 번호 ',
    'shop.order_placed_desc1_after': ' 가 생성되었습니다.',
    'shop.track_order': '주문 상태 확인: ',
    'shop.my_orders': 'My > 주문 내역',
    'shop.go_to_shopping': '쇼핑 계속하기',
    'shop.not_available': '해당 없음',
    'shop.msg_select_size': '사이즈를 선택해 주세요',
    'shop.configure_your': '당신의',
    'shop.preference': '선택 사항을 구성하세요.',
    'shop.opt_range': '범위',
    'shop.opt_step': '단계',
    'shop.chat_inquiry_prefix': '[상품 문의]',
    'shop.chat_order_prefix': '[주문 완료]',
    'shop.chat_payment_prefix': '[입금 완료 보고]',
    'shop.chat_product_name': '상품명',
    'shop.chat_price': '가격',
    'shop.chat_brand': '브랜드',
    'shop.chat_link': '링크',
    'shop.chat_order_no': '주문 번호',
    'shop.chat_option': '옵션',
    'shop.chat_amount': '금액',
    'shop.chat_depositor': '입금자',
    'shop.chat_payment_msg': '입금을 완료했습니다. 확인 부탁드려요!',
    'shop.msg_chat_failed': '채팅을 시작하지 못했습니다. 다시 시도해 주세요.',
    'shop.msg_order_failed': '주문을 생성하지 못했습니다. 다시 시도해 주세요.',

    // My
    'my.access_denied': '접근 거부됨',
    'my.sign_in_required': '프로필을 보려면 로그인해 주세요.',
    'my.go_home': '홈으로 이동',
    'my.profile_photo': '프로필 사진',
    'my.default_nickname': '모험가',
    'my.role_instructor': '강사',
    'my.role_seller': '판매자',
    'my.role_pro': '전문가',
    'my.default_bio': '정회원',
    'my.login_method': '로그인 방법',
    'my.gender': '성별',
    'my.gender_other': '기타',
    'my.email_address': '이메일 주소',
    'my.cell_phone': '휴대폰 번호',
    'my.not_linked': '연동되지 않음',
    'my.pro_status': '전문가 상태',
    'my.verified': '인증됨',
    'my.verified_desc': '기본 정보가 보안 팀에 의해 인증되었습니다.',
    'my.additional_verification': '추가 인증',
    'my.apply_badge': '고급 배지 신청',
    'my.modify_profile': '프로필 수정',
    'my.modify_profile_desc': '계정 외형 및 개인 정보 수정',
    'my.access_rights': '접근 권한',
    'my.instructor_desc': '라이브 세션 개설 및 커리큘럼 관리 권한이 있습니다.',
    'my.seller_desc': '마켓플레이스 및 재고 관리 도구에 대한 전체 접근 권한이 있습니다.',
    'my.pro_desc': '전문 서비스 등록 및 예약 관리 기능이 있습니다.',
    'my.logout': '로그아웃',
    'my.gender_male': '남성',
    'my.gender_female': '여성',
    'my.auth_google': '구글',
    'my.auth_email': '이메일',
    'my.auth_phone': '전화번호',

    // Wallet
    'wallet.sign_in_required': '지갑을 보려면 로그인해 주세요.',
    'wallet.current_balance': '현재 잔액',
    'wallet.points': '포인트',
    'wallet.charge': '충전',
    'wallet.send': '송금',
    'wallet.my_coupons': '내 쿠폰',
    'wallet.available': '사용 가능',
    'wallet.no_coupons': '사용 가능한 쿠폰이 없습니다.',
    'wallet.free_pass': '프리 패스',
    'wallet.discount': '할인',
    'wallet.expires': '만료일',
    'wallet.forever': '무제한',
    'wallet.use_coupon': '지금 쿠폰 사용',
    'wallet.used_on': '{date}에 사용됨',
    'wallet.expired': '만료됨',
    'wallet.recent_activity': '최근 활동',
    'wallet.no_transactions': '최근 거래 내역이 없습니다.',
    'wallet.view_all': '전체 내역 보기',
    'wallet.confirm_use_coupon': '이 쿠폰을 지금 사용하시겠습니까?',
    'wallet.coupon_used': '쿠폰이 성공적으로 사용되었습니다!',
    'wallet.coupon_fail': '쿠폰 사용에 실패했습니다.',
    'wallet.type_charge': '충전',
    'wallet.type_payment': '결제',
    'wallet.type_coupon_use': '쿠폰 사용',
    'wallet.type_refund': '환불',
    'wallet.type_gift': '선물',
    'wallet.status_completed': '완료',
    'wallet.status_pending': '대기 중',
    'wallet.status_failed': '실패',

    // History
    'history.tab_needs_action': '할 일',
    'history.tab_all': '전체',
    'history.tab_class': '클래스',
    'history.tab_social': '소셜',
    'history.tab_shop': '상점',
    'history.tab_stay': '스테이',
    'history.tab_inquiry': '문의',
    'history.tab_registration': '등록',
    'history.tab_like': '좋아요',
    'history.status_pending': '대기 중',
    'history.status_confirming': '확인 중',
    'history.status_paid': '결제됨',
    'history.date_recently': '최근',
    'history.no_pending': '대기 중인 항목 없음',
    'history.no_alerts': '최근 알림 없음',
    'history.caught_up': '모든 확인을 마쳤습니다!',
    'history.update_notify': '새로운 업데이트가 있으면 알려드릴게요.',
    'history.action_required': '조치 필요',
    'history.completed': '완료됨',
    'history.no_history': '활동 내역 없음',
    'history.no_tab_history': '{tab} 내역이 없습니다',
    'history.class_empty_desc': '클래스에 등록하여 내역을 확인해 보세요!',
    'history.coming_soon': '더 많은 내역이 준비 중입니다.',
    'history.confirm_payment': '결제 확인',
    'history.verifying': '결제 확인 중...',
    'history.app_details': '신청 상세 정보',
    'history.app_id': '신청 ID',
    'history.timeline': '진행 타임라인',
    'history.step_submitted': '신청서 제출',
    'history.step_reported': '입금 보고됨',
    'history.step_complete': '등록 완료',
    'history.waiting_payment': '입금 대기 중',
    'history.pending_admin': '관리자 확인 대기 중',
    'history.info_bundle': '번들 정보',
    'history.info_pass': '월간 패스 정보',
    'history.info_class': '클래스 정보',
    'history.instructor': '강사',
    'history.venue': '장소',
    'history.schedule': '일정',
    'history.sessions': '세션',
    'history.included_classes': '포함된 클래스',
    'history.loading': '상세 정보 로딩 중...',
    'history.payment_details': '결제 정보',
    'history.method': '결제 방법',
    'history.bank_transfer': '무통장 입금',
    'history.total_amount': '총 금액',
    'history.transfer_info': '입금 정보',
    'history.bank': '은행',
    'history.account_number': '계좌 번호',
    'history.account_holder': '예금주',
    'history.transfer_prompt': '자리를 확보하려면 입금을 완료해 주세요.',
    'history.modal_title': '입금 보고',
    'history.modal_desc': '입금자명과 날짜를 입력해 주세요.',
    'history.depositor_name': '입금자명',
    'history.deposit_date': '입금 날짜',
    'history.cancel': '취소',
    'history.confirm': '확인',
    'history.name_placeholder': '예: 홍길동',
    'history.toast_error_input': '입금자명과 날짜를 입력해 주세요.',
    'history.toast_success_report': '입금 보고가 제출되었습니다.',
    'history.toast_success_desc': '관리자 확인 후 최종 완료됩니다.',
    'history.toast_error_process': '처리 중 오류가 발생했습니다.',
    'history.toast_copy_account': '계좌 번호가 클립보드에 복사되었습니다.',

    // MyInfo
    'myinfo.photo_change': '사진 변경',
    'myinfo.photo_delete': '삭제',
    'myinfo.uploading': '업로드 중...',
    'myinfo.optimizing': '최적화 중...',
    'myinfo.save_success': '프로필이 성공적으로 저장되었습니다.',
    'myinfo.save_error': '프로필 저장에 실패했습니다.',
    'myinfo.personal_details': '개인 정보 상세',
    'myinfo.full_name_en': '성명 (영문)',
    'myinfo.native_name': '성명 (현지어 - 선택)',
    'myinfo.native_name_placeholder': '예: 알렉산더',
    'myinfo.bio': '전문 타이틀 및 소개',
    'myinfo.contact_info': '연락처 정보',
    'myinfo.email': '이메일 주소',
    'myinfo.verified': '인증됨',
    'myinfo.cell_phone': '휴대폰 번호',
    'myinfo.allow_calls': '전화 통화 허용',
    'myinfo.allow_calls_on': '켬',
    'myinfo.allow_calls_off': '끔',
    'myinfo.allow_calls_desc': '참고: 활성화하면 프로필에 통화 버튼이 나타납니다. 실제 전화번호는 노출되지 않습니다.',
    'myinfo.gender': '성별',
    'myinfo.gender_male': '남성',
    'myinfo.gender_female': '여성',
    'myinfo.gender_other': '기타',
    'myinfo.roles': '역할',
    'myinfo.roles_multi_select': '다중 선택 가능',
    'myinfo.role_instructor_label': '강사',
    'myinfo.role_instructor_sub': '콘텐츠 생성 및 관리',
    'myinfo.role_seller_label': '판매자',
    'myinfo.role_seller_sub': '상품 등록 및 판매',
    'myinfo.role_pro_label': '서비스 제공자',
    'myinfo.role_pro_sub': '전문 서비스 제공',
    'myinfo.deactivate_account': '계정 비활성화',
    'myinfo.deactivate_desc': '계정을 비활성화하면 프로필이 일시적으로 중단됩니다.',
    'myinfo.deactivate_btn': '비활성화',
    'myinfo.saving': '변경 사항 저장 중...',
    'myinfo.save_changes': '변경 사항 저장',
    'myinfo.photo_upload_complete': '사진 업로드 완료! 저장을 눌러 마무리하세요.',
    'myinfo.photo_upload_fail': '사진 업로드 실패. 다시 시도해 주세요.',
    'myinfo.photo_size_error': '파일이 너무 큽니다. 최대 10MB까지 허용됩니다.',

    // Deactivate
    'deactivate.title': '계정 비활성화',
    'deactivate.warning_desc': '계정을 비활성화하면 프로필과 정보가 다른 사용자에게 숨겨집니다. 보낸 메시지 등 일부 정보는 계속 보일 수 있습니다.',
    'deactivate.warning_grace_period': '30일 이내에 다시 로그인하여 취소할 수 있습니다.',
    'deactivate.profile_hidden_label': '프로필 숨김',
    'deactivate.grace_period_label': '30일 유예 기간',
    'deactivate.grace_period_desc': '30일 후에는 데이터가 영구 삭제됩니다.',
    'deactivate.confirm_btn': '지금 비활성화',
    'deactivate.cancel_btn': '계정 유지하기',

    // Resale
    'resale.create_title': '에코 게시하기',
    'resale.create_label': '중고 상품',
    'resale.posting': '게시 중',
    'resale.submit_btn': '아이템 공유하기',
    'resale.add_photo': '아이템 사진 추가',
    'resale.what_sharing': '무엇을 공유하시나요?',
    'resale.title_placeholder': '예: 빈티지 핸드페인팅 부채',
    'resale.category': '카테고리',
    'resale.price': '가격 (₩)',
    'resale.location': '장소',
    'resale.condition': '상태',
    'resale.trade_method': '거래 방법',
    'resale.price_offer': '가격 제안',
    'resale.negotiation_ok': '가격 제안 가능',
    'resale.fixed_price': '가격 고정',
    'resale.story': '아이템 이야기',
    'resale.story_placeholder': '아이템의 역사와 현재 상태에 대해 알려주세요...',
    'resale.seoul_korea': '대한민국 서울',
    'resale.cat_all': '전체',
    'resale.cat_shoes': '슈즈',
    'resale.cat_apparel': '의류',
    'resale.cat_accessories': '액세서리',
    'resale.cat_equipment': '장비',
    'resale.cat_others': '기타',
    'resale.cond_s': '새 상품',
    'resale.cond_a': '거의 새 것',
    'resale.cond_b': '상태 좋음',
    'resale.cond_c': '사용감 있음',
    'resale.trade_direct': '직거래',
    'resale.trade_delivery': '글로벌 배송',
    'resale.trade_both': '둘 다 가능',
    'resale.manner_temp': '매너 온도',
    'resale.label_location': '장소:',
    'resale.chat_with_seller': '판매자와 채팅하기',
    'resale.chat_info_auto': '상품 정보가 자동으로 전송됩니다',
    'resale.btn_reserve': '예약하기',
    'resale.btn_cancel': '취소',
    'resale.btn_mark_sold': '판매 완료로 표시',
    'resale.btn_sold_out': '판매 완료',
    'resale.btn_buy_now': '지금 구매',
    'resale.just_now': '방금 전',
    'resale.mins_ago': '분 전',
    'resale.hours_ago': '시간 전',
    'resale.days_ago': '일 전',
    'resale.order_summary': '주문 요약',
    'resale.label_condition': '상태:',
    'resale.contact_number': '연락처',
    'resale.no_contact_number': '연락처 정보 없음',
    'resale.contact_info_desc': '판매자가 구매에 대해 이 번호로 연락드릴 것입니다.',
    'resale.processing': '처리 중...',
    'resale.confirm_price': '확인 · ₩',
    'resale.confirm_desc': '확인을 누르면 판매자에게 구매 요청이 전송됩니다.',
    'resale.purchase_requested': '구매 요청 완료!',
    'resale.purchase_requested_desc': '구매 요청이 판매자에게 전달되었습니다.\\n판매자가 곧 연락드릴 것입니다.',
    'resale.go_to_resale': '리세일로 이동',
    'resale.no_activity': '활동 없음',
    'resale.in_progress_count': ' 진행 중, ',
    'resale.pending_count': ' 대기 중, ',
    'resale.liked_count': ' 좋아요',
    'resale.clear_all': '전체 삭제',
    'resale.badge_in_progress': '진행 중',
    'resale.badge_pending': '대기 중',
    'resale.no_activity_found': '활동 내역을 찾을 수 없습니다.',
    'resale.sort_latest': '최신순',
    'resale.sort_popular': '인기순',
    'resale.sort_price_asc': '가격 낮은순 ↑',
    'resale.sort_price_desc': '가격 높은순 ↓',
    'resale.items_count': '상품',
    'resale.person': '판매자',
    'resale.filter_by_person': '판매자별 필터',
    'resale.sort': '정렬',
    'resale.have_items_share': '공유할 아이템이 있나요?',
    'resale.post_item': '아이템 게시',
    'resale.no_image': '이미지 없음',
    'resale.no_items_found': '상품을 찾을 수 없습니다',
    'resale.msg_fill_required': '모든 필수 항목을 입력하고 사진을 추가해 주세요.',
    'resale.msg_post_failed': '아이템 게시 실패. 다시 시도해 주세요.',
    'resale.msg_update_failed': '상태 업데이트에 실패했습니다.',
    'resale.msg_share_unsupported': '이 기기에서는 공유를 지원하지 않습니다.',
    'resale.msg_login_chat': '채팅하려면 로그인해 주세요.',
    'resale.msg_no_self_chat': '자기 자신과는 채팅할 수 없습니다',
    'resale.msg_confirm_chat': '판매자와 채팅을 시작하시겠습니까?',
    'resale.msg_chat_failed': '채팅을 시작하지 못했습니다.',
    'resale.msg_login_like': '좋아요를 누르려면 로그인해 주세요.',
    'resale.msg_login_like_items': '좋아요를 누르려면 로그인해 주세요.',
    'resale.msg_enter_phone': '판매자가 연락할 수 있도록 연락처를 입력해 주세요.',
    'resale.msg_purchase_failed': '구매 요청 실패. 다시 시도해 주세요.',
    'resale.confirm_clear_wishlist': '위시리스트를 모두 비우시겠습니까?',
    'resale.chat_inquiry_prefix': '[상품 문의]',
    'resale.chat_item_name': '상품명',
    'resale.chat_price': '가격',
    'resale.chat_link': '링크',
    'resale.status_active': '판매 중',
    'resale.status_reserved': '예약 중',
    'resale.status_sold': '판매 완료',
    'resale.status_sold_out': '품절',
    'resale.search_items': '상품 또는 판매자 검색...',

    // Rental
    'rental.sort_latest': '최신순',
    'rental.sort_price_asc': '가격 낮은순',
    'rental.sort_popular': '인기순',
    'rental.size_all': '전체',
    'rental.size_very_large': '매우 큼',
    'rental.size_large': '큼',
    'rental.size_medium': '보통',
    'rental.size_small': '작음',
    'rental.size_very_small': '매우 작음',
    'rental.size_extra_large': '매우 큼',
    'rental.stats_spaces': '공간',
    'rental.filter_studio': '스튜디오',
    'rental.filter_sort': '정렬',
    'rental.filter_title_studio': '스튜디오 필터',
    'rental.filter_close': '필터 닫기',
};

async function sync() {
    try {
        const missingKeysData = JSON.parse(fs.readFileSync(MISSING_KEYS_PATH, 'utf8'));
        let contextContent = fs.readFileSync(LANGUAGE_CONTEXT_PATH, 'utf8');

        // Locate KR dictionary block
        const krStartMarker = 'KR: {';
        const krStartIndex = contextContent.indexOf(krStartMarker);
        
        if (krStartIndex === -1) {
            console.error('Could not find KR dictionary block');
            return;
        }

        const insertIndex = krStartIndex + krStartMarker.length;
        
        let newEntries = '\n';
        let count = 0;
        for (const key in missingKeysData) {
            const translation = translationMap[key] || missingKeysData[key];
            // Escape single quotes if necessary
            const escapedTranslation = translation.replace(/'/g, "\\'");
            newEntries += `    '${key}': '${escapedTranslation}',\n`;
            count++;
        }

        const updatedContent = contextContent.slice(0, insertIndex) + newEntries + contextContent.slice(insertIndex);

        fs.writeFileSync(LANGUAGE_CONTEXT_PATH, updatedContent, 'utf8');
        console.log(`Successfully injected ${count} keys into LanguageContext.tsx`);

    } catch (error) {
        console.error('Sync failed:', error);
    }
}

sync();
