/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#b31b25",
        "surface-bright": "#f7f5ff",
        "primary-fixed-dim": "#5391ff",
        "secondary-fixed-dim": "#b4c1ff",
        "secondary": "#3a53b7",
        "on-secondary-container": "#223ea2",
        "surface-container-highest": "#d6dbff",
        "on-tertiary-fixed-variant": "#681c73",
        "inverse-primary": "#4d8eff",
        "on-secondary-fixed": "#00278f",
        "surface-container": "#e4e7ff",
        "on-primary": "#f0f2ff",
        "on-error-container": "#570008",
        "background": "#f7f5ff",
        "surface-container-low": "#efefff",
        "secondary-container": "#c7cfff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#2d48ac",
        "error-dim": "#9f0519",
        "on-error": "#ffefee",
        "tertiary-dim": "#7b2f85",
        "inverse-surface": "#020a2f",
        "tertiary-fixed": "#f199f7",
        "secondary-dim": "#2c47ab",
        "primary": "#0057bd",
        "inverse-on-surface": "#929bc6",
        "surface-container-high": "#dde1ff",
        "on-surface-variant": "#515981",
        "on-tertiary-fixed": "#3e0047",
        "surface-variant": "#d6dbff",
        "surface": "#f7f5ff",
        "primary-container": "#6e9fff",
        "tertiary": "#893c92",
        "tertiary-fixed-dim": "#e28ce9",
        "on-primary-fixed-variant": "#002a62",
        "on-primary-fixed": "#000000",
        "tertiary-container": "#f199f7",
        "on-surface": "#242c51",
        "on-background": "#242c51",
        "primary-dim": "#004ca6",
        "outline": "#6c759e",
        "surface-tint": "#0057bd",
        "on-secondary": "#f2f1ff",
        "error-container": "#fb5151",
        "secondary-fixed": "#c7cfff",
        "on-tertiary-container": "#5e106a",
        "on-tertiary": "#ffeefb",
        "primary-fixed": "#6e9fff",
        "surface-dim": "#cad2ff",
        "outline-variant": "#a3abd7",
        "on-primary-container": "#002150"
      },
      boxShadow: {
        '3xl': '0 35px 60px -15px rgba(0, 0, 0, 0.1)',
        '4xl': '0 45px 80px -20px rgba(0, 0, 0, 0.15)',
        'premium': '0 20px 50px -10px rgba(0, 0, 0, 0.05)',
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    require("tailwindcss-animate"),
  ],
};
