/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d3dbdd",
        "surface-container-high": "#e4e9ea",
        "on-tertiary-container": "#595c5f",
        "on-secondary": "#f6f9ff",
        "primary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#e3e5e8",
        "on-error-container": "#752121",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#0058ba",
        "surface": "#f9f9f9",
        "on-primary": "#f7f7ff",
        "on-tertiary-fixed": "#474a4d",
        "error-container": "#fe8983",
        "on-surface": "#2d3435",
        "on-error": "#fff7f6",
        "on-tertiary-fixed-variant": "#636669",
        "background": "#f9f9f9",
        "tertiary-container": "#f2f4f7",
        "on-surface-variant": "#596061",
        "outline-variant": "#acb3b4",
        "on-primary-container": "#004fa8",
        "primary-fixed-dim": "#c2d4ff",
        "on-secondary-fixed-variant": "#585c61",
        "tertiary-fixed": "#f2f4f7",
        "primary": "#005BC0",
        "on-secondary-container": "#4e5257",
        "on-primary-fixed": "#003d85",
        "tertiary": "#5c5f62",
        "secondary-fixed": "#dfe3e8",
        "secondary": "#5b5f64",
        "surface-variant": "#dde4e5",
        "surface-tint": "#005BC0",
        "secondary-container": "#dfe3e8",
        "inverse-surface": "#0c0f0f",
        "surface-container-low": "#f2f4f4",
        "outline": "#757c7d",
        "inverse-primary": "#4a8eff",
        "secondary-fixed-dim": "#d1d5da",
        "primary-container": "#d8e2ff",
        "inverse-on-surface": "#9c9d9d",
        "surface-container-highest": "#dde4e5",
        "on-tertiary": "#f7f9fc",
        "error": "#9f403d",
        "on-secondary-fixed": "#3c4044",
        "on-background": "#2d3435",
        "surface-bright": "#f9f9f9",
        "surface-container": "#ebeeef"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
